language: python

python:
  - 2.7
  - 3.3

env:
  - DJANGO_VERSION=1.4.10
  - DJANGO_VERSION=1.5.5
  - DJANGO_VERSION=1.6

matrix:
  exclude:
   - python: 3.3
     env: DJANGO_VERSION=1.4.10
   - python: 3.3
     env: DJANGO_VERSION=1.5.5

install:
   # GeoDjango dependencies
 - sudo apt-get install -y python-software-properties
 - sudo apt-add-repository -y ppa:ubuntugis/ppa
 - sudo apt-get update > /dev/null
 - sudo apt-get install -y libgdal-dev libproj-dev libgeos-dev libspatialite-dev
 - pip install git+git://github.com/tinio/pysqlite.git@extension-enabled#egg=pysqlite

   # This is a dependency of our Django test script
 - pip install argparse --use-mirrors

 - pip install -q Django==$DJANGO_VERSION --use-mirrors

 - pip install coverage

 - pip install flake8 --use-mirrors

 - python setup.py develop
 - npm install leaflet/tests/

before_script:
 - flake8 --ignore=E501 leaflet

script:
 - python quicktest.py leaflet
 - node node_modules/django-leaflet-tests/node_modules/mocha-phantomjs/bin/mocha-phantomjs leaflet/tests/index.html

after_success:
 - coverage run quicktest.py leaflet
 - pip install coveralls
 - coveralls
