sudo: required
language: python
cache: pip

addons:
  postgresql: '10'
  apt:
    packages:
      - postgresql-10-postgis-2.5
      - postgresql-10-postgis-2.5-scripts

env:
  - DATABASE=postgres

matrix:
  fast_finish: true
  include:
    - { python: "2.7", env: DJANGO=1.8 }
    - { python: "3.3", env: DJANGO=1.8 }
    - { python: "3.4", env: DJANGO=1.8 }
    - { python: "3.5", env: DJANGO=1.8 }

    - { python: "2.7", env: DJANGO=1.9 }
    - { python: "3.4", env: DJANGO=1.9 }
    - { python: "3.5", env: DJANGO=1.9 }

    - { python: "2.7", env: DJANGO=1.10 }
    - { python: "3.4", env: DJANGO=1.10 }
    - { python: "3.5", env: DJANGO=1.10 }

    - { python: "2.7", env: DJANGO=1.11 }
    - { python: "3.4", env: DJANGO=1.11 }
    - { python: "3.5", env: DJANGO=1.11 }
    - { python: "3.6", env: DJANGO=1.11 }
    - { python: "3.7", env: DJANGO=1.11 }

    - { python: "3.4", env: DJANGO=2.0 }
    - { python: "3.5", env: DJANGO=2.0 }
    - { python: "3.6", env: DJANGO=2.0 }
    - { python: "3.7", env: DJANGO=2.0 }

    - { python: "3.5", env: DJANGO=2.1 }
    - { python: "3.6", env: DJANGO=2.1 }
    - { python: "3.7", env: DJANGO=2.1 }

    - { python: "3.5", env: DJANGO=2.2 }
    - { python: "3.6", env: DJANGO=2.2 }
    - { python: "3.7", env: DJANGO=2.2 }

    - { python: "3.7", env: DJANGO=2.2 DATABASE=sqlite SPATIALITE_LIBRARY_PATH='mod_spatialite' }

    - { python: "3.5", env: DJANGO=master }
    - { python: "3.6", env: DJANGO=master }
    - { python: "3.7", env: DJANGO=master }


  allow_failures:
    - env: DJANGO=master

before_install:
  - sudo apt-get update

install:
 # GeoDjango dependencies
 - sudo apt-get update -qq
 - sudo apt-get install -y libproj-dev libgeos-dev

 - if [[ $DATABASE == sqlite ]]; then sudo apt-get install -y libspatialite-dev libsqlite3-mod-spatialite; fi
 - if [ $DATABASE == sqlite ] && [ $TRAVIS_PYTHON_VERSION == 2.7 ]; then pip install pysqlite==2.8.3; fi
 - if [[ $DATABASE == postgres ]]; then pip install psycopg2-binary; fi

 - pip install tox tox-travis flake8
 - python setup.py develop
 - npm install leaflet/tests/

 - pip freeze
 - dpkg -l

before_script:
 - flake8 --ignore=E501,W504 leaflet
 - if [[ $DATABASE == postgres ]]; then psql -c 'create database test_db;' -U postgres; fi
 - if [[ $DATABASE == postgres ]]; then psql -c 'CREATE EXTENSION postgis;' -U postgres -d test_db; fi

script:
 - tox
 - node --version
 - node node_modules/mocha-phantomjs/bin/mocha-phantomjs leaflet/tests/index.html

after_success:
 - pip install coveralls
 - coveralls
